### ISSUE TITLE
createComp方法没有导出

### ISSUE THREAD

**Issue by gaolizheng** [shangdibaozi/ECS#10]
createComp方法没有导出，register.test.ts文件中调用ecs.createComp会报错

**Comment by dgflash** [comment]
ecs.Entity.add(组件对象类型名）这样创建。设计时就不导出。createComp
你是有什么特殊场景要这样用，可以说明下。




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "shangdibaozi/ECS"                                                                                    ***@***.***&gt;;
Date:&nbsp;Mon, Jun 13, 2022 11:27 AM
***@***.***&gt;;
***@***.***&gt;;
Subject:&nbsp;[shangdibaozi/ECS] createComp方法没有导出 (Issue #10)





 
createComp方法没有导出，register.test.ts文件中调用ecs.createComp会报错

**Comment by gaolizheng** [comment]
哦，没有，就是register.test.ts里会有报错，我理解你的意思

**Comment by dgflash** [comment]
好的，有问题以后可以在交流群中聊，方便点。




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "shangdibaozi/ECS"                                                                                    ***@***.***&gt;;
Date:&nbsp;Mon, Jun 13, 2022 11:54 AM
***@***.***&gt;;
***@***.******@***.***&gt;;
Subject:&nbsp;Re: [shangdibaozi/ECS] createComp方法没有导出 (Issue #10)





 
哦，没有，就是register.test.ts里会有报错，我理解你的意思

**Comment by gaolizheng** [comment]
> 好的，有问题以后可以在交流群中聊，方便点。
> […](#)
> ------------------&nbsp;Original&nbsp;------------------ From: "shangdibaozi/ECS" ***@***.***&gt;; Date:&nbsp;Mon, Jun 13, 2022 11:54 AM ***@***.***&gt;; ***@***.******@***.***&gt;; Subject:&nbsp;Re: [shangdibaozi/ECS] createComp方法没有导出 (Issue #10) 哦，没有，就是register.test.ts里会有报错，我理解你的意思 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

交流群是？我加一下

**Comment by dgflash** [comment]
QQ群：798575969




------------------&nbsp;Original&nbsp;------------------
From:                                                                                                                        "shangdibaozi/ECS"                                                                                    ***@***.***&gt;;
Date:&nbsp;Mon, Jun 13, 2022 02:23 PM
***@***.***&gt;;
***@***.******@***.***&gt;;
Subject:&nbsp;Re: [shangdibaozi/ECS] createComp方法没有导出 (Issue #10)





  
好的，有问题以后可以在交流群中聊，方便点。
 …
 ------------------&nbsp;Original&nbsp;------------------ From: "shangdibaozi/ECS" @.&gt;; Date:&nbsp;Mon, Jun 13, 2022 11:54 AM @.&gt;; @.@.&gt;; Subject:&nbsp;Re: [shangdibaozi/ECS] createComp方法没有导出 (Issue #10) 哦，没有，就是register.test.ts里会有报错，我理解你的意思 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
  
交流群是？我加一下
